[rewrite_local]
# 酷狗广告
^https:\/\/gateway\.kugou\.com\/ads\.gateway\/v3\/mine_link url reject-dict
^http:\/\/gateway\.kugou\.com\/adp\/ad\/v1\/mine_top_banner url reject-dict
^http:\/\/gateway\.kugou\.com\/ads\.gateway url reject-dict
# 掌上英雄联盟
^http:\/\/us\.l\.qq\.com\/exapp\?adposcount url reject-dict
[mitm]
hostname = gateway.kugou.com,us.l.qq.com